version: '3.7'

networks:
  app-ntw:

services:
  mysql:
    image: mariadb:5.5
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - app-ntw
    ports:
      - "3308:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      TYPEORM_CONNECTION: mysql
      TYPEORM_HOST: mysql
      TYPEORM_PORT: 3306
      TYPEORM_USERNAME: test
      TYPEORM_PASSWORD: test
      TYPEORM_DATABASE: test
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - app-ntw

  webserver:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - "./nginx/local.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-ntw

volumes:
  mysql: