apiVersion: v1
kind: Service
metadata:
  name: cloud-infrastructure-svc
  labels:
    app: cloud-infrastructure-app
spec:
  type: NodePort
  selector:
    app: cloud-infrastructure-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32001
